# Generated by Django 5.0 on 2024-02-02 19:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.garment_image_file_path),
        ),
    ]
